/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author mateu
 */
public class RelatorisoMenuView extends javax.swing.JFrame {

    /**
     * Creates new form RelatorisoMenuView
     */
    public RelatorisoMenuView() {
        initComponents();
    }

    /**
     * Getters para os botões.
     */
    public JButton getBntArecadacaoMes() {
        return bntArecadacaoMes;
    }

    public JButton getBntRankingClientes() {
        return bntRankingClientes;
    }

    public JButton getBntReceitaEstacionamento() {
        return bntReceitaEstacionamento1;
    }

    public JButton getBtnVoltar() {
        return btnSair;
    }

    public JButton getBntRankingVagas() {
        return bntRankingVagas;
    }

    public JButton getBtnHistoricoCliente() {
        return BtnHistoricoCliente;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntRankingClientes = new javax.swing.JButton();
        bntRankingVagas = new javax.swing.JButton();
        bntArecadacaoMes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        bntReceitaEstacionamento1 = new javax.swing.JButton();
        BtnHistoricoCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntRankingClientes.setText("Ranking de clientes");
        bntRankingClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRankingClientesActionPerformed(evt);
            }
        });

        bntRankingVagas.setText("Ranking de Vagas");
        bntRankingVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRankingVagasActionPerformed(evt);
            }
        });

        bntArecadacaoMes.setText("Arecadação por mes ");

        btnSair.setText("Voltar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        bntReceitaEstacionamento1.setText("Receita estacinamento");
        bntReceitaEstacionamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReceitaEstacionamento1ActionPerformed(evt);
            }
        });

        BtnHistoricoCliente.setText("Historico de Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnSair))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bntRankingVagas, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addComponent(BtnHistoricoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bntRankingClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntArecadacaoMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntReceitaEstacionamento1)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addGap(30, 30, 30)
                .addComponent(bntRankingClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntArecadacaoMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntReceitaEstacionamento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRankingVagas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnHistoricoCliente)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRankingClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRankingClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRankingClientesActionPerformed

    private void bntRankingVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRankingVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRankingVagasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void bntReceitaEstacionamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReceitaEstacionamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntReceitaEstacionamento1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorisoMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorisoMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorisoMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorisoMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorisoMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHistoricoCliente;
    private javax.swing.JButton bntArecadacaoMes;
    private javax.swing.JButton bntRankingClientes;
    private javax.swing.JButton bntRankingVagas;
    private javax.swing.JButton bntReceitaEstacionamento1;
    private javax.swing.JButton btnSair;
    // End of variables declaration//GEN-END:variables

}
